import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const leads = [
  {
    nome: "Ana Paula Ferreira",
    email: "ana.ferreira@gmail.com",
    telefone: "(11) 98234-5678",
    paraQuem: "familia",
    quantidadePessoas: "2-4",
    faixaEtaria: "36-55",
    prioridade: "cobertura",
    orcamento: "50-99",
    planoRecomendado: "familia",
    contatado: true,
    criadoEm: new Date("2025-05-10T09:14:00"),
  },
  {
    nome: "Roberto Carlos Almeida",
    email: "roberto.almeida@hotmail.com",
    telefone: "(21) 97654-3210",
    paraQuem: "familia",
    quantidadePessoas: "5+",
    faixaEtaria: "56-70",
    prioridade: "servicos",
    orcamento: "100-199",
    planoRecomendado: "premium",
    contatado: false,
    criadoEm: new Date("2025-05-12T14:32:00"),
  },
  {
    nome: "Mariana Costa Souza",
    email: "mariana.souza@yahoo.com.br",
    telefone: "(31) 99123-4567",
    paraQuem: "eu",
    quantidadePessoas: "1",
    faixaEtaria: "18-35",
    prioridade: "preco",
    orcamento: "ate-49",
    planoRecomendado: "essencial",
    contatado: true,
    criadoEm: new Date("2025-05-13T11:05:00"),
  },
  {
    nome: "Jorge Luís Santos",
    email: "jorge.santos@gmail.com",
    telefone: "(51) 98765-4321",
    paraQuem: "familia",
    quantidadePessoas: "2-4",
    faixaEtaria: "36-55",
    prioridade: "cobertura",
    orcamento: "50-99",
    planoRecomendado: "familia",
    contatado: false,
    criadoEm: new Date("2025-05-14T08:47:00"),
  },
  {
    nome: "Fernanda Lima Oliveira",
    email: "fernanda.lima@gmail.com",
    telefone: "(85) 99234-8765",
    paraQuem: "familia",
    quantidadePessoas: "5+",
    faixaEtaria: "56-70",
    prioridade: "servicos",
    orcamento: "200+",
    planoRecomendado: "premium",
    contatado: false,
    criadoEm: new Date("2025-05-14T16:20:00"),
  },
  {
    nome: "Carlos Eduardo Ramos",
    email: "carlos.ramos@empresa.com.br",
    telefone: "(41) 98456-1234",
    paraQuem: "familia",
    quantidadePessoas: "2-4",
    faixaEtaria: "36-55",
    prioridade: "cobertura",
    orcamento: "100-199",
    planoRecomendado: "premium",
    contatado: true,
    criadoEm: new Date("2025-05-15T10:30:00"),
  },
  {
    nome: "Beatriz Mendes Rodrigues",
    email: "beatriz.mendes@gmail.com",
    telefone: "(62) 97890-5432",
    paraQuem: "eu",
    quantidadePessoas: "1",
    faixaEtaria: "18-35",
    prioridade: "preco",
    orcamento: "ate-49",
    planoRecomendado: "essencial",
    contatado: false,
    criadoEm: new Date("2025-05-15T13:58:00"),
  },
  {
    nome: "Paulo Henrique Teixeira",
    email: "paulo.teixeira@outlook.com",
    telefone: "(19) 99312-6789",
    paraQuem: "familia",
    quantidadePessoas: "2-4",
    faixaEtaria: "56-70",
    prioridade: "cobertura",
    orcamento: "50-99",
    planoRecomendado: "familia",
    contatado: false,
    criadoEm: new Date("2025-05-16T09:10:00"),
  },
  {
    nome: "Luciana Vieira Pereira",
    email: "luciana.vieira@gmail.com",
    telefone: "(11) 96543-2109",
    paraQuem: "familia",
    quantidadePessoas: "5+",
    faixaEtaria: "70+",
    prioridade: "servicos",
    orcamento: "200+",
    planoRecomendado: "premium",
    contatado: true,
    criadoEm: new Date("2025-05-16T15:45:00"),
  },
  {
    nome: "Thiago Nascimento Cruz",
    email: "thiago.cruz@gmail.com",
    telefone: "(71) 98901-3456",
    paraQuem: "eu",
    quantidadePessoas: "1",
    faixaEtaria: "36-55",
    prioridade: "preco",
    orcamento: "50-99",
    planoRecomendado: "essencial",
    contatado: false,
    criadoEm: new Date("2025-05-17T07:22:00"),
  },
];

async function main() {
  console.log("Inserindo dados fictícios...");
  await prisma.simulacao.createMany({ data: leads });
  console.log(`✓ ${leads.length} leads inseridos com sucesso.`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
