import { NextRequest } from "next/server";
import { prisma } from "@/lib/db";

const DEFAULT_PARCEIROS = [
  {
    nome: "Santa Mônica Centro Clínico",
    tipo: "Saúde e Exames",
    desconto: "Até 32% em Consultas e Exames",
    contato: "(61) 3618-9100 | Q. 13 L. 27 Jd. Brasília",
    logoUrl: null,
    ativo: true,
    ordem: 0,
  },
  {
    nome: "Drogarias Santa Saúde",
    tipo: "Farmácia",
    desconto: "Até 60% de desconto",
    contato: "(61) 99192-0737 | Q. 5 L. 23 Lj. 06 Mansões Águas Lindas",
    logoUrl: null,
    ativo: true,
    ordem: 1,
  },
  {
    nome: "Lapac Laboratório",
    tipo: "Exames e Laboratório",
    desconto: "Desconto previsto em tabela",
    contato: "(61) 3083-9850 | Várias Unidades",
    logoUrl: null,
    ativo: true,
    ordem: 2,
  },
  {
    nome: "Centramed",
    tipo: "Exames e Laboratório",
    desconto: "30% de desconto em exames laboratoriais",
    contato: "(61) 98533-2011",
    logoUrl: null,
    ativo: true,
    ordem: 3,
  },
  {
    nome: "Centro de Diagnóstico Belle",
    tipo: "Exames e Laboratório",
    desconto: "Descontos previstos em tabela",
    contato: "(61) 3613-8699 | (61) 98626-0659",
    logoUrl: null,
    ativo: true,
    ordem: 4,
  },
  {
    nome: "Aliança Diagnóstico Clínico",
    tipo: "Exames e Laboratório",
    desconto: "Até 50% de desconto",
    contato: "(61) 3618-8580 | (61) 98595-0221",
    logoUrl: null,
    ativo: true,
    ordem: 5,
  },
  {
    nome: "Laboratório Unilab",
    tipo: "Exames e Laboratório",
    desconto: "Até 20% de desconto",
    contato: "(61) 3618-9100 | (61) 3391-4636",
    logoUrl: null,
    ativo: true,
    ordem: 6,
  },
  {
    nome: "Laboratório Herman's",
    tipo: "Exames e Laboratório",
    desconto: "Até 25% de desconto",
    contato: "(61) 3613-0406",
    logoUrl: null,
    ativo: true,
    ordem: 7,
  },
  {
    nome: "DOCX Radiologia",
    tipo: "Exames e Laboratório",
    desconto: "Até 15% de desconto",
    contato: "(61) 3613-6133 | (61) 99814-0848",
    logoUrl: null,
    ativo: true,
    ordem: 8,
  },
  {
    nome: "Padrão Diagnóstico por Imagem",
    tipo: "Exames e Laboratório",
    desconto: "10% de desconto nos exames",
    contato: "(61) 99522-9595 | (61) 99432-8111",
    logoUrl: null,
    ativo: true,
    ordem: 9,
  },
  {
    nome: "Ampare Psicologia e Nutrição",
    tipo: "Saúde e Exames",
    desconto: "20% de desconto nos atendimentos",
    contato: "(61) 3964-2265 | (61) 99826-1035",
    logoUrl: null,
    ativo: true,
    ordem: 10,
  },
  {
    nome: "Lojão das Clínicas",
    tipo: "Artigos Hospitalares",
    desconto: "Até 15% de desconto",
    contato: "(61) 3618-1331 | (61) 98281-2530",
    logoUrl: null,
    ativo: true,
    ordem: 11,
  },
  {
    nome: "Oftalmed Hospital de Visão",
    tipo: "Exames e Laboratório",
    desconto: "Tabela de desconto em consultas/exames",
    contato: "(61) 2191-9191",
    logoUrl: null,
    ativo: true,
    ordem: 12,
  },
  {
    nome: "Visão Hospital de Olhos",
    tipo: "Exames e Laboratório",
    desconto: "De 10% a 50% de desconto",
    contato: "(61) 3038-8001",
    logoUrl: null,
    ativo: true,
    ordem: 13,
  },
  {
    nome: "Ópticas Dinando",
    tipo: "Ópticas",
    desconto: "20% de desconto em exames",
    contato: "(61) 3613-4000",
    logoUrl: null,
    ativo: true,
    ordem: 14,
  },
  {
    nome: "Elefanttu's Fast Food",
    tipo: "Lazer e Alimentação",
    desconto: "5% de desconto em todo o cardápio",
    contato: "(61) 3616-1818 | (61) 3613-6204",
    logoUrl: null,
    ativo: true,
    ordem: 15,
  },
  {
    nome: "Manacá Odontologia Especializada",
    tipo: "Odontologia",
    desconto: "15% de desconto em procedimentos",
    contato: "(61) 3618-3810 | (61) 99238-4611",
    logoUrl: null,
    ativo: true,
    ordem: 16,
  },
  {
    nome: "Odontonei Dentistas",
    tipo: "Odontologia",
    desconto: "De 10% até 35% de desconto",
    contato: "(61) 98551-9874 | (61) 99280-7461",
    logoUrl: null,
    ativo: true,
    ordem: 17,
  },
  {
    nome: "Orthodontic",
    tipo: "Odontologia",
    desconto: "Até 30% de desconto",
    contato: "(61) 3618-2545",
    logoUrl: null,
    ativo: true,
    ordem: 18,
  },
  {
    nome: "Odonto Forte",
    tipo: "Odontologia",
    desconto: "15% de desconto",
    contato: "(61) 99826-9583",
    logoUrl: null,
    ativo: true,
    ordem: 19,
  },
  {
    nome: "AmaFisio",
    tipo: "Saúde e Exames",
    desconto: "Desconto de 5% + Avaliação gratuita",
    contato: "(61) 3613-6707 | (61) 99933-2867",
    logoUrl: null,
    ativo: true,
    ordem: 20,
  },
  {
    nome: "Dido Gás",
    tipo: "Comércio",
    desconto: "10% de desconto com entrega",
    contato: "(61) 3616-2616 | (61) 99308-7149",
    logoUrl: null,
    ativo: true,
    ordem: 21,
  },
  {
    nome: "Gás JK",
    tipo: "Comércio",
    desconto: "10% de desconto com entrega",
    contato: "(61) 3618-3386 | (61) 99292-9235",
    logoUrl: null,
    ativo: true,
    ordem: 22,
  },
  {
    nome: "Pérola Gás",
    tipo: "Comércio",
    desconto: "10% de desconto com entrega",
    contato: "(61) 3618-0075 | (61) 99192-6600",
    logoUrl: null,
    ativo: true,
    ordem: 23,
  },
  {
    nome: "Mundo do Estudante",
    tipo: "Papelaria",
    desconto: "5% a prazo e 10% à vista",
    contato: "(61) 3613-8262",
    logoUrl: null,
    ativo: true,
    ordem: 24,
  },
  {
    nome: "Antonietti Advocacia",
    tipo: "Serviços",
    desconto: "Franqueado 50% pela Amavidas",
    contato: "(61) 98348-6395 | (61) 99576-6667",
    logoUrl: null,
    ativo: true,
    ordem: 25,
  },
  {
    nome: "Faculdade Filos",
    tipo: "Educação",
    desconto: "Até 55% de desconto",
    contato: "(61) 3618-1452",
    logoUrl: null,
    ativo: true,
    ordem: 26,
  },
  {
    nome: "Colégio Filos",
    tipo: "Educação",
    desconto: "No mínimo 10% de desconto",
    contato: "(61) 3618-1452",
    logoUrl: null,
    ativo: true,
    ordem: 27,
  },
  {
    nome: "Faculdade Mauá Goiás",
    tipo: "Educação",
    desconto: "Até 70% de desconto",
    contato: "(61) 3613-0423",
    logoUrl: null,
    ativo: true,
    ordem: 28,
  },
  {
    nome: "Centro Car / A.P Pneus",
    tipo: "Serviços",
    desconto: "25% em mão de obra + balanceamento/alinhamento",
    contato: "(61) 99212-2539 | (61) 99129-9458",
    logoUrl: null,
    ativo: true,
    ordem: 29,
  },
  {
    nome: "Mecânica Gonça",
    tipo: "Serviços",
    desconto: "30% de desconto na mão de obra",
    contato: "(61) 99350-2505",
    logoUrl: null,
    ativo: true,
    ordem: 30,
  },
  {
    nome: "Dave Vieira Seguros",
    tipo: "Serviços",
    desconto: "Até 20% de desconto",
    contato: "(61) 98209-1520",
    logoUrl: null,
    ativo: true,
    ordem: 31,
  },
  {
    nome: "Contabilidade Vila Nova",
    tipo: "Serviços",
    desconto: "Até 40% de desconto",
    contato: "(61) 99261-1398",
    logoUrl: null,
    ativo: true,
    ordem: 32,
  },
  {
    nome: "Mayara Verônica Imóveis",
    tipo: "Serviços",
    desconto: "10% em avaliação judicial de imóveis",
    contato: "(61) 99986-3984",
    logoUrl: null,
    ativo: true,
    ordem: 33,
  },
  {
    nome: "Al Telecom",
    tipo: "Serviços",
    desconto: "12% de desconto nos serviços prestados",
    contato: "(61) 3613-2982 | (61) 99397-1928",
    logoUrl: null,
    ativo: true,
    ordem: 34,
  },
  {
    nome: "Waltenis Internet Globo Wifi",
    tipo: "Serviços",
    desconto: "5% de desconto",
    contato: "(61) 99185-3190",
    logoUrl: null,
    ativo: true,
    ordem: 35,
  },
  {
    nome: "CDL Águas Lindas de Goiás",
    tipo: "Serviços",
    desconto: "10% de desconto",
    contato: "(61) 99853-1062",
    logoUrl: null,
    ativo: true,
    ordem: 36,
  },
  {
    nome: "RC Segurança Eletrônica",
    tipo: "Serviços",
    desconto: "Até 15% de desconto",
    contato: "(61) 99918-9081 | (61) 99981-1430",
    logoUrl: null,
    ativo: true,
    ordem: 37,
  },
  {
    nome: "Gráfica Pioneira",
    tipo: "Serviços",
    desconto: "Até 10% de desconto (exceto material promocional)",
    contato: "(61) 3613-1494 | (61) 99262-4527",
    logoUrl: null,
    ativo: true,
    ordem: 38,
  },
  {
    nome: "M.A Consultoria",
    tipo: "Serviços",
    desconto: "Até 50% de desconto",
    contato: "(61) 99689-3333 | (61) 99448-1313",
    logoUrl: null,
    ativo: true,
    ordem: 39,
  },
];

async function ensureSeed() {
  if ((await prisma.parceiro.count()) === 0) {
    await prisma.parceiro.createMany({ data: DEFAULT_PARCEIROS });
  }
}

export async function GET(req: NextRequest) {
  try {
    await ensureSeed();
    const parceiros = await prisma.parceiro.findMany({
      where: { ativo: true },
      orderBy: [
        { ordem: "asc" },
        { criadoEm: "desc" }
      ]
    });
    return Response.json({ parceiros });
  } catch (error) {
    console.error("Erro ao buscar parceiros públicos:", error);
    return Response.json({ error: "Erro ao buscar parceiros" }, { status: 500 });
  }
}
